version: '3.9'
services:

  mariadb:
    container_name: simple.mariadb
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'default'
    ports:
     - 3306:3306
   
  nginx:
    container_name: simple.nginx
    build:
      context: ~/docker/simple
    ports:
      - 8080:8080
    volumes:
      - project:/var/www:delegated
    networks:
      default:
        aliases:
          - simple.local
    
  volumes:
    - project:~/docker/simple
