version: '3.9'
services:

  mariadb:
    container_name: simple.mariadb
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'default'
      TZ: Europe/Moscow
    ports:
      - "3306:3306"

  nginx:
    container_name: simple.nginx
    build:
      context: .
      args:
        ENV: production # development or production
    environment:
      TZ: Europe/Moscow
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www:delegated
